export GIT_BYPASS = 1
export PARALLEL_SYNTH = 8

# Define target part
export PRJ_PART = XCU55N-FSVH2892-2L-E

export REMOVE_UNUSED_CODE = 1
export USE_XVC_DEBUG = 1

# Define target output
target: prom

# Use top level makefile
include ../shared_config.mk
include ../../submodules/ruckus/system_vivado.mk
